---
title: "Blog Post 9"
date: "5/3/2020"
output: 
  html_document:
    theme: united
---

Need something to make you smile? Watch this:

<iframe width="560" height="315" src="https://www.youtube.com/embed/Terhj8mjPwY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

the opening number won an Emmy Award for Outstanding Original Music and Lyrics in 2009. I love Hugh Jackman. 


I was listening to Hamilton and I just thought of something. In the first act Hamilton and Burr both have songs that introduce who they are /their actions/temperaments (”My Shot” & “Wait For It”)  and in the second act we have songs that give us a reason for why they are that way (”The Room Where It Happens” & “Hurricane”). It is so much like life like how when you are young (Act one) you don’t have time for self reflection and when you get older (Act two) you do and can. Both ”My Shot” & “Wait For It” are  about how Hamilton and Burr want to be viewed by others, something that younger people care a lot about.  In act two ”The Room Where It Happens” & “Hurricane” are both also for the most part told in first person and here the songs are true admissions of their motives and reflections about why they are who they are to the audience and to others in the play and most importantly to themselves. The change in tone of songs from the first act to the second act does not only reflect going from war and revolution to peace and nation building but this shift also reflects Burr and Hamilton getting older and growing up and changing. They are no longer the brash womanizing young soldiers we meet in the first act because the war and simply the passage of time has changed them and by that point we as an audience have also changed by seeing the story unfold. In this process of growing up, such as life, they become more themselves but also have a more refined fragile picture of who that is and a final understanding of their motives. I think that is what makes this show so relatable because while it is about a life ( Hamilton’s), it is also more about life in general. When it ends you are left asking what it means to live a complete life because I just sat and listened to a man’s life unfold for 2 and half hours so “what is this life?”. I’m probably completely wrong with this analysis because I’m an idiot but this is how I like to think about it. 


