---
title:  "Blog Post 1"
output: 
  html_document:
    theme: cerulean
    code_folding: hide
---
Two weeks left until I go back to school and I have to finish studying for the GRE Math subject test and that sucks ass. I feel like I spent a whole summer studying for 2 tests that mean nothing but also mean everything at the same time.

I should  have been studying for the math GRE subject test but I spent an hour listening to Hugh Laurie and David Silverman. If you want to listen to a humorous and rational converstation about atheism for an hour...

<iframe width="560" height="315" src="https://www.youtube.com/embed/dX6T1O_EKAc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>


I also recently read Josh Radnor's article for "ThriveGlobal" on spirituality and love it. I don't believe in god or spirits but his article is so beautifully well written and hopeful that it is captivating even though flawed. 

(https://www.thriveglobal.com/stories/40092-actor-and-musician-josh-radnor-on-how-spirituality-has-changed-his-life)


I also have gotten really into listening to  "Randor & Lee." 

<iframe width="560" height="315" src="https://www.youtube.com/embed/EAORjS28btQ" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

My favorite song is their song "Here"^[https://open.spotify.com/album/78NRQY6Yfi9Narn1b8kZAe].


I've also been reading alot of articles on fivethirtyeight and their model for the House elections 2018 gives the Democrats a 3/4 chance of flipping the house. 

(https://projects.fivethirtyeight.com/2018-midterm-election-forecast/house/)

Here is the podcast of Nate Silver explaining the model^[https://fivethirtyeight.com/features/politics-podcast-lets-talk-about-the-2018-house-forecast/?ex_cid=navlink]: 

<iframe frameborder="0" width="100%" height="180" style="margin:20px auto 25px;max-width:600px;" scrolling="no" src="https://fivethirtyeight.com/player/politics/24394034/"></iframe> 


