---
title: "Blog Post 6"
output: 
  html_document:
    theme: cerulean

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggthemes)
library(readr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(lubridate)
library(rvest)
```

so we are in lockdown and the world ending.

<iframe width="560" height="315" src="https://www.youtube.com/embed/4n1GT-VjjVs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

```{r,echo=FALSE,warning=FALSE,message=FALSE}
covid_deaths <- read_csv("covid-deaths.csv")
covid_deaths<-as.data.frame(covid_deaths)
dates <- mdy("03-24-2020") - days(1:85)
date<- sort(dates)
us_deaths<-covid_deaths%>%
  filter(Entity== "United States")%>%
  rename(deaths = "Total confirmed deaths (deaths)", day = "Year") 
us_deaths<-cbind(us_deaths,date)
us_deaths<-us_deaths %>%
  filter(date>=mdy("02-25-2020"))
ggplot(data = us_deaths, aes(x=date,y=deaths))+
  geom_point(color ="blue") +
  geom_smooth(color="green") +
  ggtitle("Total Number of U.S. Deaths of Covid-19")
```
data  sourced from European Centre for Disease Prevention and Control (ECDC)^[https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide]
 (by way of "Our World in Data"^[https://ourworldindata.org/coronavirus-data])

## reproduction rates of different diseases: 

```{r,echo=FALSE,warning=FALSE,message=FALSE}
options(scipen = 0)
curve(2.65^(x),from = 0, to = 10, n = 10000,type="l",col="red",ylab="number of cases",main="COVID-19")
curve(2.1^(x),from = 0, to = 10, n = 10000,col="green",ylab="number of cases", main ="1918 H1N1 strain")
curve(2^(x),from = 0, to = 10, n = 10000,col="blue",ylab="number of cases", main ="Ebola")
curve(1.5^(x),from = 0, to = 10, n = 10000,col="dark green",ylab="number of cases",main="2009 H1N1 strain")
curve(1.3^(x),from = 0, to = 10, n = 10000,col="orange",ylab="number of cases",main="seasonal flu")
```

I just used the reproduction rate found here^[https://en.wikipedia.org/wiki/Basic_reproduction_number]

## more fun charts: Avengers

using this data from fivethirtyeight^[https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv]

^[https://fivethirtyeight.com/features/avengers-death-comics-age-of-ultron/]
```{r,echo=FALSE,warning=FALSE,message=FALSE}
d<-read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv")
d<-as.data.frame(d)
mod1<-lm(data = d,Appearances~Gender+Years.since.joining+Death1)
```



```{r,echo=FALSE,warning=FALSE,message=FALSE}
ggplot(d, aes(x = Years.since.joining, y = Appearances, color = Death1,shape=Gender))+
  geom_point()+
  ggtitle("Avengers")
```



```{r,echo=FALSE,warning=FALSE,message=FALSE}
ggplot(d, aes(x = interaction(Gender, Death1), y = Appearances, color = Death1, shape=Gender))+
  geom_boxplot() +
  theme_fivethirtyeight(base_size = 12, base_family = "sans")+
  ggtitle("Avengers: Death x Gender")
```

```{r,echo=FALSE,warning=FALSE,message=FALSE}
ggplot(d, aes(x = Death1, y = Appearances, 
                    group = Gender, 
                    linetype = Gender, 
                    shape = Gender,
                    color = Gender)) +
  geom_jitter(height = 0, width = 0.03, alpha = .7) +
  geom_smooth(method = "lm", se = 0)
```
