---
title: "Plots"
output: 
  html_document:
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(tidyverse)
library(babynames)
library(ggplot2)
library(extrafont)
library(ggthemes)
library(RColorBrewer)
library(gridExtra)
library(rmarkdown)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
guns_polls <- read_csv("guns-polls.csv")
#making sure numeric variables are treated as numeric
guns_polls$Republican<-as.integer(guns_polls$`Republican Support`)
guns_polls$Democratic<-as.integer(guns_polls$`Democratic Support`)
guns<- guns_polls%>%
    filter(Question == "stricter-gun-laws") 


ggplot(data = guns, aes(x = Democratic)) +
   geom_point(aes(y = Republican, color = Pollster, shape = Population), size = 5) +
  theme_solarized(light = FALSE) +
  ggtitle("stricter gun laws")
    
```
^[https://github.com/fivethirtyeight/data/blob/master/poll-quiz-guns/guns-polls.csv]

```{r, message=FALSE, warning=FALSE, echo=FALSE}
Thanksgiving <- read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/thanksgiving-2015/thanksgiving-2015-poll-data.csv") 
  

Thanksgiving_maindish <- data.frame(table(Thanksgiving$`What is typically the main dish at your Thanksgiving dinner?`)) %>%
  filter(Freq > 5)

p<-ggplot(data=Thanksgiving_maindish, aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity", fill = "Orange") +
  theme_fivethirtyeight() +
  ggtitle("Popular main dish")
p
```



```{r, message=FALSE, warning=FALSE, echo=FALSE}

cook<-Thanksgiving %>%
  filter(`What is typically the main dish at your Thanksgiving dinner?`== "Turkey")
  

Turkey_method <- data.frame(table(cook$`How is the main dish typically cooked?`)) %>%
  filter(Freq > 5)

t<-ggplot(data=Turkey_method, aes(x=Var1, y=Freq)) +
  geom_bar(stat="identity", fill = "Blue") +
  theme_fivethirtyeight() +
  ggtitle("How do you cook your turkey?")
t
```

```{r,echo=FALSE,warning=FALSE,message=FALSE}
d<-read.csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv")
d<-as.data.frame(d)
mod1<-lm(data = d,Appearances~Gender+Years.since.joining+Death1)
```



```{r,echo=FALSE,warning=FALSE,message=FALSE}
ggplot(d, aes(x = Years.since.joining, y = Appearances, color = Death1,shape=Gender))+
  geom_point()+
  ggtitle("Avengers")
```



```{r,echo=FALSE,warning=FALSE,message=FALSE}
ggplot(d, aes(x = interaction(Gender, Death1), y = Appearances, color = Death1, shape=Gender))+
  geom_boxplot() +
  theme_fivethirtyeight(base_size = 12, base_family = "sans")+
  ggtitle("Avengers: Death x Gender")
```
^["https://raw.githubusercontent.com/fivethirtyeight/data/master/thanksgiving-2015/thanksgiving-2015-poll-data.csv"]


```{r,echo=FALSE,warning=FALSE,message=FALSE}
ggplot(d, aes(x = Death1, y = Appearances, 
                    group = Gender, 
                    linetype = Gender, 
                    shape = Gender,
                    color = Gender)) +
  geom_jitter(height = 0, width = 0.03, alpha = .7) +
  geom_smooth(method = "lm", se = 0)
```

using this data from fivethirtyeight^[https://raw.githubusercontent.com/fivethirtyeight/data/master/avengers/avengers.csv]

^[https://fivethirtyeight.com/features/avengers-death-comics-age-of-ultron/]






