---
title: "Résumé"
output: 
  html_document:
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)

```


### contact info:
$\textbf{Email:}$ julialee64@gmail.com 

$\textbf{Github:}$ https://github.com/JuliaClaireLee

$\textbf{Linkedin:}$ 
https://www.linkedin.com/in/julia-lee-5201b0156/

# EDUCATION

#### Smith College, Northampton, MA
B.A. 2019, Statistical and Data Sciences and Mathematics\
- GPA: Overall - 3.56 \
- Statistics major: 3.90 \

#### University of California, Riverside, Riverside, CA
M.S. Statistics, July 2019 - December 2022

# Relevant graduate coursework: 
Statistical Computing, Advanced Statistical Computing, Discrete Data Analysis, Theory of Probability sequence , Regression, Anova, and Design sequence, Multivariate Analysis  

# Relevant undergraduate coursework:  
Mathematical Statistics, Linear Algebra, Advanced Linear Algebra, Machine Learning, Research Design and Analysis, Multiple Regression, Probability, Communicating with Data, Intro to Computer Science, Intro to Data Science, Intro to Probability and Statistics, Statistical and Data Science Capstone Project

# SKILLS

R (proficient) | SQL (proficient)  | Tableau (proficient)
Git (proficient) | Python (working knowledge) | CSS (working knowledge)
HTML (working knowledge) |Java (basic skills)

# PROJECTS

Project using R to build Shiny App to create an interactive dashboard to view real time weather data in a user-friendly format. The data came from MacLeish Field Station in Whately, MA, and also included historical data. In creating the dashboard, I created a new R package (“CEEDS”) that had functions to deal with weather data. (Senior Capstone project)  



Longitudinal Project, “Predicting Mental Health Outcomes,” using three methods--decision trees, logistic regression, and smoothing splines--to compare variables over time in order to study factors that predict future mental health in midlife. 

# WORK EXPERIENCE

#### Senior Statistician | UCLA Health
June 2023 - December 2023 \
 
- Conducted data wrangling and data transformation. \

- Performed statistical analyses from both large and small samples of data. \ 

- Perform the work of statistical programming in R

####  Analyst, Data and Programming Intern | Pancreatic Cancer Action Network
March - June 2023 \

- Paid internship with largest pancreatic cancer nonprofit that monitors treatment trials \

- Track various aspects of clinical trials\

- Used machine learning techniques for enrollment prediction.


#### Data Science Intern | Loopie
July 2021 - March 2022

- Created a Shiny App to extract and organize data for the sales team. \

- Perform other data assignments involving the analysis of consumer and other business data. \

- Analyzed customer and revenue data to build data visualizations and infographics for quarterly reports


#### Infographics and Data Analytics Associate | Pima County Justice for All, Tucson, AZ 

February 2021 – March 2022\

- Extracted and researched public data for use in a campaign to provide legal counsel to immigrants. \

- Designed charts, graphs, maps and other visual aids to present on social media.


#### Graduate Teaching Assistant |  University of California, Riverside, Statistics Department     

Sept. 2020 - March 2021 \ 

- Taught R, a statistical computing language in computer science lab component of Statistics 100A and Statistics 100B. 

##### Student Grader | Smith College Math Department	

September 2018 - May 2019 \

- Linear Algebra and Calculus II	           


### REFERENCES FURNISHED UPON REQUEST

