---
title: "R_0"
output: 
  html_document:
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(ggthemes)
library(readr)
library(tidyverse)
library(tidyr)
library(dplyr)
library(lubridate)
library(rvest)
```
   

```{r,echo=FALSE,warning=FALSE,message=FALSE}
covid_deaths <- read_csv("covid-deaths.csv")
covid_deaths<-as.data.frame(covid_deaths)
dates <- mdy("03-24-2020") - days(1:85)
date<- sort(dates)
us_deaths<-covid_deaths%>%
  filter(Entity== "United States")%>%
  rename(deaths = "Total confirmed deaths (deaths)", day = "Year") 
us_deaths<-cbind(us_deaths,date)
us_deaths<-us_deaths %>%
  filter(date>=mdy("02-25-2020"))
ggplot(data = us_deaths, aes(x=date,y=deaths))+
  geom_point(color ="blue") +
  geom_smooth(color="green") +
  ggtitle("Total Number of U.S. Deaths of Covid-19")
```
data  sourced from European Centre for Disease Prevention and Control (ECDC)^[https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide]
 (by way of "Our World in Data"^[https://ourworldindata.org/coronavirus-data])
 
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">This is the best and clearest explanation of why people need to stay at home you could ever wish to see <a href="https://t.co/49MgadlctI">pic.twitter.com/49MgadlctI</a></p>&mdash; Alan White (@aljwhite) <a href="https://twitter.com/aljwhite/status/1241859943017349126?ref_src=twsrc%5Etfw">March 22, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

<iframe src="https://julia-lee.shinyapps.io/exponential/" width="100%" height="400px"></iframe>


## reproduction rates of different diseases: 

```{r,echo=FALSE,warning=FALSE,message=FALSE}
options(scipen = 0)
curve(2.65^(x),from = 0, to = 10, n = 10000,type="l",col="red",ylab="number of cases",main="COVID-19")
curve(2.1^(x),from = 0, to = 10, n = 10000,col="green",ylab="number of cases", main ="1918 H1N1 strain")
curve(2^(x),from = 0, to = 10, n = 10000,col="blue",ylab="number of cases", main ="Ebola")
curve(1.5^(x),from = 0, to = 10, n = 10000,col="dark green",ylab="number of cases",main="2009 H1N1 strain")
curve(1.3^(x),from = 0, to = 10, n = 10000,col="orange",ylab="number of cases",main="seasonal flu")
```

I just used the reproduction rate found here^[https://en.wikipedia.org/wiki/Basic_reproduction_number]