---
title: "Blog Post 2"
output: 
  html_document:
    theme: united
---
I sent in my application for my absentee ballot for the midterm elections.^[https://votesaveamerica.com/] 


Lawrence O'Donnell gave this beautiful monologue about progress on the eve of the infamous election of 2016 and it has stuck with me for the 21 months since. Brooklyn will win on Nov.6.2018.^[https://twitter.com/thelastword/status/795845829143605249] 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Hillary Clinton isn’t the only one on the verge of making history tomorrow: <a href="https://twitter.com/Lawrence?ref_src=twsrc%5Etfw">@Lawrence</a> shares his <a href="https://twitter.com/hashtag/lastword?src=hash&amp;ref_src=twsrc%5Etfw">#lastword</a> on the 2016 campaign &amp; Brooklyn. <a href="https://t.co/0v9Uw0OSUd">pic.twitter.com/0v9Uw0OSUd</a></p>&mdash; The Last Word (@TheLastWord) <a href="https://twitter.com/TheLastWord/status/795845829143605249?ref_src=twsrc%5Etfw">November 8, 2016</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

As election day nears, we should all keep in mind that "The World Is Wide Enough" for different political points of view. I disagree with the  unjust and ignorant racist opinions that the GOP hold but we can't stoop to the level of Trump and his Fox News minions. They want us to believe that only their views can exist and everything else is fake news and rigged. This fall we will peacefully vote them out of power.

<iframe width="560" height="315" src="https://www.youtube.com/embed/BQ1ZwqaXJaQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>^[https://www.youtube.com/embed/BQ1ZwqaXJaQ]


Beto O'Rourke gave the most beautiful and honest answer about NFL players kneeling for racial justice. He is this generation's Bobby Kennedy^[https://www.irishcentral.com/news/politics/beto-orourke-bobby-kennedy]. 

<iframe width="560" height="315" src="https://www.youtube.com/embed/lAw9eXXVwfM" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

