---
title: "Words, Words, Words"
output: 
  html_document:
    theme: cerulean
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(readr)
library(tidyverse)
library(mdsr)
require(devtools)
library(ggthemes)
library(ggplot2)
library(ggthemes)
library(RColorBrewer)
library(gridExtra)
library(rmarkdown)
library(wordcloud)
library(tm)
#install.packages("RCurl")
library(RCurl)
```

# The Declaration Of Independence

```{r, message=FALSE, warning=FALSE, echo=FALSE}
pal <- brewer.pal(15, "Blues")
DeclarationofIndependence_url <-"http://www.constitution.org/usdeclar.txt"
DeclarationofIndependence_Raw<-RCurl::getURL(DeclarationofIndependence_url)
DeclarationofIndependence<-VCorpus(VectorSource(DeclarationofIndependence_Raw)) 
DeclarationofIndependence<-DeclarationofIndependence %>%
  tm_map(removeWords, stopwords("english")) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
wordcloud(DeclarationofIndependence, max.words = Inf, random.order=FALSE, min.freq = 2, scale = c(4,0.00115), colors = pal)
```

# The Odyssey

```{r, message=FALSE, warning=FALSE,echo=FALSE}
pal2 <- brewer.pal(8,"Dark2")
odyssey_url<-"https://www.clear.rice.edu/comp200/resources/texts/odyssey.txt"
odyssey_Raw<-RCurl::getURL(odyssey_url)
odyssey<-VCorpus(VectorSource(odyssey_Raw)) 
odyssey<-odyssey %>%
  tm_map(removeWords, stopwords("english")) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
wordcloud(odyssey, max.words = Inf, scale = c(4,0.00975125),random.order=FALSE,rot.per=.15, colors =pal2 )
```


# Kennedy Inaugural Address

```{r, message=FALSE, warning=FALSE,echo=FALSE}
pal3 <- brewer.pal(8,"Pastel1")
Kennedy_url<-"https://www.clear.rice.edu/comp200/resources/texts/Kennedy%20Inaugural%20Address.txt"
Kennedy_Raw<-RCurl::getURL(Kennedy_url)
Kennedy<-VCorpus(VectorSource(Kennedy_Raw)) 
Kennedy<-Kennedy%>%
  tm_map(removeWords, stopwords("english")) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace)
wordcloud(Kennedy, max.words = Inf, scale = c(7, 0.125), random.order=FALSE, rot.per=.15, colors =pal3)
```

# Constitution

```{r, message=FALSE, warning=FALSE, echo=FALSE}
usconstitution_url<-"https://www.usconstitution.net/const.txt"
usconstitution_Raw<-RCurl::getURL(usconstitution_url)
usconstitution<-VCorpus(VectorSource(usconstitution_Raw)) 

usconstitution<-usconstitution %>%
  tm_map(removeWords, stopwords("english")) %>%
  tm_map(removePunctuation) %>%
  tm_map(stripWhitespace) %>%
  tm_map(removeNumbers)
wordcloud(usconstitution, max.words = Inf, scale = c(6,0.41),random.order=FALSE, rot.per=.15, colors =pal2, random.color = TRUE )
```






